-- 005-002-enable-rls.sql
-- T027: Enable Row Level Security on dual auth & related tables

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE polar_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE mapbox_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_tool_invocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_server_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_drift_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE stream_playback_deny ENABLE ROW LEVEL SECURITY;
